---
- name: to check target
  hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: copy war file
      copy:
         src: /home/ansible/testfresher.war
         dest: /root/apache-tomcat-9.0.95/webapps


